### ISSUE TITLE
Evaluation fails when an object named `env` exists in a parent namespace

### ISSUE THREAD

**Issue by cpsievert** [hadley/lazyeval#84]
Transferring the issue from here https://github.com/HenrikBengtsson/R.utils/issues/60

``` r
> env <- NA
> lazyeval::f_eval(~ 1 + 2 + 3)
Error in .Call(env, f) : 
  first argument must be a string (of length 1) or native symbol reference
In addition: Warning message:
failed to assign NativeSymbolInfo for env since env is already defined in the ‘lazyeval’ namespace 
> session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin13.4.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2016-10-05                  

Packages -----------------------------------------------------------------------
 package     * version date       source                            
 colorout      1.1-2   2016-05-10 Github (jalvesaq/colorout@6538970)
 devtools    * 1.12.0  2016-06-24 CRAN (R 3.3.0)                    
 digest        0.6.10  2016-08-02 cran (@0.6.10)                    
 fortunes      1.5-3   2016-05-20 CRAN (R 3.3.0)                    
 htmltools     0.3.5   2016-03-21 CRAN (R 3.3.0)                    
 htmlwidgets   0.7     2016-08-02 cran (@0.7)                       
 inline        0.3.14  2015-04-13 CRAN (R 3.3.0)                    
 lazyeval      0.2.0   2016-06-12 CRAN (R 3.3.0)                    
 memoise       1.0.0   2016-01-29 CRAN (R 3.3.0)                    
 Rcpp          0.12.7  2016-09-05 CRAN (R 3.3.1)                    
 withr         1.0.2   2016-06-20 CRAN (R 3.3.0)  
```

**Comment by Alanocallaghan** [comment]
This issue would exist whenever env exists before lazyeval is loaded.

    library(gdata)
    library(lazyeval)
    Warning message:
      failed to assign NativeSymbolInfo for env since env is already defined in the ‘lazyeval’ namespace 

    plotly::plot_ly(mtcars, ~a)
    Error in .Call(env, f) : 
      first argument must be a string (of length 1) or native symbol reference

As far as I can tell, using a string rather than a native symbol reference in `f_env` would ensure consistent functionality

**Comment by hadley** [comment]
A string is definitely not the right answer, because it might find an `env` native symbol reference in the wrong package. More investigation is needed - this feels like an R bug to me

```R
> env <- NA
> library(lazyeval)
Warning message:
failed to assign NativeSymbolInfo for env since env is already defined in the ‘lazyeval’ namespace 
```

**Comment by hadley** [comment]
Possibly related: https://github.com/hadley/purrr/issues/197

**Comment by Alanocallaghan** [comment]
Also probably related: https://github.com/hadley/dplyr/issues/2153

**Comment by wch** [comment]
It looks like it was a bug in R that's fixed:  https://github.com/wch/r-source/commit/685c05e7c7dc86b6a3641f1811a4eff502080e18

Also relevant: https://stat.ethz.ch/pipermail/r-devel/2016-July/072911.html

**Comment by wch** [comment]
But because it's a bug in R, you'll need to add workarounds and keep them around for a long time.

**Comment by Alanocallaghan** [comment]
Resolved in R-3.3.2

**Comment by romanhaa** [comment]
I'm still experiencing this issue in R-3.4.0 (see issue #97).
